### PR TITLE
Initial Gitea bridge.

### PR DESCRIPTION
**Pull request by tianyuanhao**
This a just a preview. Not all features are expected to work.

Refs #349

### CODE REVIEW

**Comment by 6543** [comment]
Thanks, was still on my list but had no time ...

If there are gitea related questions just ask :)

**Comment by MichaelMure** [comment]
This is cool!

Just as a FYI, I'd advise you to take inspiration from the Github bridge first before the others as it's the best well done yet. The others are a bit lagging behind in term of features and correctness.

I marked your PR as draft for now so that you can signal to me when you are happy with your code by marking it as ready.

**Comment by Vitali64** [comment]
Will it work for gogs?

~vitali64

**Comment by 6543** [comment]
gogs only provide an api for issues ... so and it's mostly the same ... - so *it should* work

**Comment by bqv** [comment]
A ping, in case any progress here can be made

**Comment by gc-ss** [comment]
> A ping, in case any progress here can be made

+1

**Comment by MichaelMure** [comment]
Replaced by https://github.com/MichaelMure/git-bug/pull/890 as the original repo has been deleted.

**Pull request closed without merging**
