### PR TITLE
Use Timeline API instead of raw operations

### LINKED ISSUE #94: WebUI needs to be migrated to use the Timeline
After editing the first comment (aka description) of an issue `git bug show $ID` correctly shows the latest version of that comment.

The WebUI however, only shows the first version of that comment.

### PR DESCRIPTION
**Pull request by sandhose**
Fixes #94 

The webui now uses the `Timeline` API instead of the raw `Operation`s.

### CODE REVIEW

**Comment by MichaelMure** [comment]
:+1: :+1:

**Comment by MichaelMure** [comment]
@sandhose can we merge this so the webUI is less broken than before ?

**Comment by sandhose** [comment]
image

The timeline now looks like this.

I haven't packed the assets to avoid conflicts.

**Comment by MichaelMure** [comment]
Super cool, thanks !

**Pull request merged**
