### PR TITLE
Fix github bridge import

### PR DESCRIPTION
**Pull request by rng-dynamics**
Supersedes #516

Deals with #385

### CODE REVIEW

**Comment by bqv** [comment]
(and potentially #315)

**Comment by MichaelMure** [comment]
@rng-dynamics are you done with it now?

**Review by MichaelMure — APPROVED** [review]
LGTM! Looks simpler indeed.

**Comment by MichaelMure** [comment]
fix #385

**Comment by MichaelMure** [comment]
Based on what you have seen working on this, what's missing? I'd say maybe preloading and rate-limiting handling (#315).

**Comment by rng-dynamics** [comment]
> @rng-dynamics are you done with it now?

I am done with it.

**Comment by rng-dynamics** [comment]
> Based on what you have seen working on this, what's missing? I'd say maybe preloading and rate-limiting handling (#315).

Rate-limiting seems to be the biggest problem. The current implementation does not use the rate-limit points in a very economic way. I am already working on a new version which should be able to pull more issues while consuming less rate-limit points. Nevertheless, for repositories with a big number of issues we will probably have to introduce some kind of waiting when the rate-limit points are exhausted.
Preloading is also on my todo-list.

**Comment by MichaelMure** [comment]
:tada: :+1:

**Pull request merged**
