### PR TITLE
Tests for the github bridge

### PR DESCRIPTION
**Pull request by rng-dynamics**
I wrote an integration test for the github bridge. It creates a few issues, comments, labels, edits a comment, and uses two identities. It is a simple "happy path" of an import. If you like it, we can extend it to cover more code of the importer.

This request depends on #694, i.e., #694 should be merged first.

### CODE REVIEW

**Comment by rng-dynamics** [comment]
I will mark this as a draft as long as #694 is not merged.

**Comment by MichaelMure** [comment]
@rng-dynamics go ahead and merge what you feel makes sense for the github bridge. You know better than anyone what makes sense there :)

**Comment by MichaelMure** [comment]
Again, sorry but I just can't be a proper project lead currently. I'll come back to it though.

**Comment by rng-dynamics** [comment]
@MichaelMure, I would need someones approval to merge. (Same as in #694.)

**Comment by MichaelMure** [comment]
Ha right, that should be good now.

**Comment by 6543** [comment]
@MichaelMure I can help you to make this more (helthy) communety driven - but I can't step fully in ... since I already do handle a lof of other projects :)

**Comment by 6543** [comment]
@MichaelMure PS: you can PM me via [mail](mailto:6543@obermui.de) or matrix (`@marddl:obermui.de`) ...

**Review by 6543 — APPROVED** [review]
manually tested -> worked

**Comment by rng-dynamics** [comment]
thanks guys

**Pull request merged**
