### PR TITLE
WebUI: Set bug labels

### LINKED ISSUE #575: WebUI - Allow to add/remove labels to issues
This feature is already available in GraphQL API.

### LINKED ISSUE #586: WebUI - Refactoring label presentation to use material-ui´s Chip component instead of a styled span
This is a first step to #575 .
Besides that, the Chip component offers more possibilities to enrich label interaction (for example, remove icon).

### PR DESCRIPTION
**Pull request by GlancingMind**
Closes #575 
Closes #586 

Changes:

- Display the color of the label in the label-filter-dropdown on the bug list page.
- Support assigning and removal of labels to bugs.
- Truncate long labels with an ellipsis to prevent layout breaks.
- Use the Material-UI chip component for labels.

Following are some pictures to demonstrate how a very long label is displayed in various parts of the UI.

image
image
image
image

### CODE REVIEW

**Comment by MichaelMure** [comment]
Looks good!

Tiny request, could you try to vertically align the bug title and the labels? In your last screenshot it looks like the title is slightly higher than the labels.

**Comment by GlancingMind** [comment]
Sure, will take a look.

**Comment by GlancingMind** [comment]
More like this? :)

image

I think our labels are even better aligned then GitHub ones. :smirk:

**Comment by MichaelMure** [comment]
:tada:

**Pull request merged**
