### PR TITLE
chore: remove refs to deprecated io/ioutil

### PR DESCRIPTION
**Pull request by testwill**

### CODE REVIEW

**Comment by sudoforge** [comment]
hey @testwill, thanks for catching this! it looks like there was an unrelated pipeline failure. can you rebase your tree on top of the latest changes?

**Comment by sudoforge** [comment]
your tree is still behind the default tree of this repository. please do the following to fetch the latest upstream tree (this assumes you are checked out on the `ioutil` branch of your repository):

```
git fetch git@github.com:MichaelMure/git-bug.git +refs/heads/master
```

then, rebase your tree on top of it:

```
git rebase FETCH_HEAD
```

finally, push to your tree again. you need to force push, rebase the commit hashes have changed. `--force-with-lease` is a safer force push (this assumes your local repository's remote for your fork is named `origin`):

```
git push --force-with-lease origin HEAD:ioutil
```

**Comment by testwill** [comment]
The ioutil branch has been synchronized with the master branch.

**Comment by sudoforge** [comment]
ah, apologies, i actually had an outdated tracking branch for `origin/master`. you're absolutely correct, this is good to go. thanks!

**Pull request merged**
