### PR TITLE
Display count of comment for each bug on bug list

### PR DESCRIPTION
**Pull request by GlancingMind**
image

### CODE REVIEW

**Comment by MichaelMure** [comment]
Looks good but for some reason on my side the icon is way more spaced from the border than on you screenshot. Does that make sense to you? I'm using Firefox.

image

**Comment by GlancingMind** [comment]
Hmm, I'm using firefox too.
I'll play around with it. Maybe I'll find the culprit.

**Comment by GlancingMind** [comment]
Found the culprit. Working on a fix :construction_worker_man:

**Comment by GlancingMind** [comment]
Solved.
For short title.
image

With long titles.
image

**Comment by MichaelMure** [comment]
Nice, it even works fairly well with a phone size screen.

**Pull request merged**
