### PR TITLE
Webui 548

### LINKED ISSUE #548: WebUI - Allow to reopen an issue
Reopen or Close button is presenting at same position according with bug status
image

### PR DESCRIPTION
**Pull request by claudioantonio**
fix #548

### CODE REVIEW

**Comment by MichaelMure** [comment]
Same, this need to be rebased on master.

**Comment by claudioantonio** [comment]
Hmmm...For this issue (#548 ), I only want to merge the commit 707d94f.

Are You suggesting me to rebase on my local master and make a new PR from it?

Another solution would be:
1. to revert this unique commit on my branch webui_538
2. stash these changes
3. create a new fork from git-bug and a new branch webui_538
4. apply stash to the new branch
5. make a new PR
Do You see any problem?

**Comment by MichaelMure** [comment]
I replied here: https://github.com/MichaelMure/git-bug/pull/547#issuecomment-773209609

`git revert` should really only be used when a commit has been merged but we realize that it was a mistake. Revert mark the fact that we are rolling back on something, and why.

For branch cooking, `rebase`, `rebase -i`, `cherry-pick`, `commit --amend` and friends should be used instead until you have the commits you want.

**Comment by claudioantonio** [comment]
Fixed!

**Comment by MichaelMure** [comment]
:+1:

**Pull request merged**
