### PR TITLE
feature: Github bridge mutation rate limit

### PR DESCRIPTION
**Pull request by rng-dynamics**
I wrote a new struct `client` which handles all the calls to the Github GraphQL API and which deals with the rate limit in a single place.

Note: work in progress; some manual testing is still needed.

### CODE REVIEW

**Comment by MichaelMure** [comment]
Cool stuff!

**Comment by rng-dynamics** [comment]
@MichaelMure: If you have any suggestions I would be happy to implement them. I linked issue #315, because it should be fixed with this pull request.

**Comment by MichaelMure** [comment]
hey @rng-dynamics, sorry for the delay. Life is super busy but should be back to normal-ish in a month.

**Comment by rng-dynamics** [comment]
no problem

**Comment by rng-dynamics** [comment]
@MichaelMure I would need someones approval to merge.

**Review by 6543 — APPROVED** [review]
as per #706

**Comment by 6543** [comment]
@rng-dynamics wana merge?

**Pull request merged**
