### PR TITLE
feat: upgrade go-git to v5.5.1

### PR DESCRIPTION
**Pull request by smoyer64**
Related to #934

### CODE REVIEW

**Comment by MichaelMure** [comment]
There is also https://github.com/MichaelMure/git-bug/pull/947, but it looks like some things are breaking in git-bug.

**Comment by smoyer64** [comment]
Yeah ... I didn't notice the one started by dependabot.  I'm tracking down the Go panic (it's the crypto checking the signing).

**Comment by smoyer64** [comment]
We should talk about what our goals are for commit signing and use cases for those who  already have keys.  This will obviously also impact how the bridges work since ideally we'd be able to verify signed commits from  the "forges".

**Comment by MichaelMure** [comment]
> We should talk about what our goals are for commit signing and use cases for those who already have keys. This will obviously also impact how the bridges work since ideally we'd be able to verify signed commits from the "forges".

Does that answer your question? https://github.com/MichaelMure/git-bug/issues/130

As for the bridges, I'd think the only interaction with keys would be to import the public keys when creating or updating the identities. That way, anyone having the matching private key would be able to adopt the identity without losing the history.

**Review by MichaelMure — APPROVED** [review]

**Comment by smoyer64** [comment]
I'll add a few comments to #130 instead of them languishing here on a closed PR.

**Pull request merged**
