### PR TITLE
Commits for issues #554, #564 and #566

### LINKED ISSUE #564: WebUI - add prerequisites to README
A proposal bringing some colors. ;-)

image

### PR DESCRIPTION
**Pull request by claudioantonio**
fixes #564 #566 #554

### CODE REVIEW

**Review by MichaelMure — CHANGES_REQUESTED** [review]
Looks good but you put the files in `/public`, which means they get packaged into the final binary (you can see them in the `packed_assets.go` file). I'm not exactly sure how the javascript build process work, but that shouldn't happen as they are just there for the readme.

**Comment by claudioantonio** [comment]
What do You think about a new folder called webui/ReadmeImages, or ReadmeImgs?
It will not be considered when creating build bundle and let clear that those images are related to the Readme file.
It´s a like when You save a full website and the browser creates a folder for the site´s images.

**Comment by MichaelMure** [comment]
That could work, but I'm starting to think that it's not worth it just to have some pretty images in a developer readme. Licensing could also be a problem as those images are covered by their own copyright. To have them in this repo we would need to explicitly mention exception to the general GPL licensing...

**Comment by claudioantonio** [comment]
No problem, @MichaelMure ! I'll remove the images from Readme. ;-)

**Comment by claudioantonio** [comment]
Pull request ready to go!

**Comment by MichaelMure** [comment]
:+1: :+1:

**Pull request merged**
