### PR TITLE
Open Collective integration in Readme

### PR DESCRIPTION
**Pull request by znarf**
Following your support request on Open Collective (1), here is an update to the Readme that I think will correct a few issues you reported.

Does that looks correct? Any feedback?
https://github.com/opencollective/git-bug/blob/opencollective/README.md

For now, I'm using the `images-preview` service which is not the live one, so please don't merge!

(1) https://github.com/opencollective/opencollective/issues/1368

### CODE REVIEW

**Comment by MichaelMure** [comment]
Answered in opencollective/opencollective#1368

**Comment by znarf** [comment]
@MichaelMure If you look at https://github.com/opencollective/git-bug/blob/opencollective/README.md The TLDR backer should now be gone. And that should be consistent with the data shown there in the Tier sidebar: https://opencollective.com/git-bug

screen shot 2019-01-18 at 14 49 36

**Comment by MichaelMure** [comment]
@znarf awesome. Should I merge the PR ?

**Comment by znarf** [comment]
@MichaelMure not yet! we need to update the the Open Collective Images service live, then update the PR to remove the "-preview" in the URLs.

**Comment by znarf** [comment]
@MichaelMure Should be good to go on my side.

**Pull request merged**
